from pydantic import BaseModel, Field


class Task(BaseModel):
    """
    Represents one autonomous task generated by the planner.
    """

    id: int = Field(description="Task sequence number")

    title: str = Field(description="Task title")

    objective: str = Field(description="Purpose of the task")